from collections.abc import Sequence

class ItemUpdate:
    def getValue(self, fieldNameOrPos: str | int) -> object | None: ...

class SubscriptionListener:
    def onItemUpdate(self, update: ItemUpdate) -> None: ...
    def onSubscription(self) -> None: ...
    def onUnsubscription(self) -> None: ...
    def onSubscriptionError(self, code: int, message: str) -> None: ...

class ClientListener:
    def onStatusChange(self, status: str) -> None: ...

class _ConnectionDetails:
    def setUser(self, user: str) -> None: ...
    def setPassword(self, password: str) -> None: ...

class Subscription:
    def __init__(self, mode: str, items: Sequence[str], fields: Sequence[str]) -> None: ...
    def setDataAdapter(self, dataAdapter: str) -> None: ...
    def addListener(self, listener: SubscriptionListener) -> None: ...

class LightstreamerClient:
    connectionDetails: _ConnectionDetails

    def __init__(self, serverAddress: str, adapterSet: str | None) -> None: ...
    def connect(self) -> None: ...
    def subscribe(self, subscription: Subscription) -> None: ...
    def unsubscribe(self, subscription: Subscription) -> None: ...
    def disconnect(self) -> None: ...
    def addListener(self, listener: ClientListener) -> None: ...
    def getStatus(self) -> str: ...
